transcodes = {
    'Amharic': 'am',
    'Arabic': 'ar',
    'Assamese': 'as',
    'Azerbaijani': 'az',
    'Basque': 'eu',
    'Belarusian': 'be',
    'Bengali': 'bn',
    'Bosnian': 'bs',
    'Bulgarian': 'bg',
    'Burmese': 'my',
    'Catalan': 'ca',
    'Chinese (PRC)': 'zh-CN',
    'Croatian': 'hr',
    'Czech': 'cs',
    'Danish': 'da',
    'Dutch': 'nl',
    'English (UK)': 'en',
    'Estonian': 'et',
    'Filipino': 'fil',
    'Finnish': 'fi',
    'French (France)': 'fr',
    'Galician': 'gl',
    'Georgian': 'ka',
    'German': 'de',
    'Greek': 'el',
    'Gujarati': 'gu',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hungarian': 'hu',
    'Indonesian': 'id',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Kannada': 'kn',
    'Kazakh': 'kk',
    'Khmer': 'km',
    'Kiswahili': 'sw',
    'Korean (South Korea)': 'ko',
    'Lao': 'lo',
    'Latvian': 'lv',
    'Lithuanian': 'lt',
    'Macedonian': 'mk',
    'Maithili': 'mai',
    'Malay': 'ms',
    'Malayalam': 'ml',
    'Maori': 'mi',
    'Marathi': 'mr',
    'Mongolian Cyrillic': 'mn',
    'Nepali': 'ne',
    'Norwegian': 'no',
    'Oriya': 'or',
    'Persian': 'fa',
    'Polish': 'pl',
    'Portuguese (Brazil)': 'pt',
    'Portuguese (Portugal)': 'pt',
    'Punjabi': 'pa',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Serbian': 'sr',
    'Sinhala': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Spanish (Latin America)': 'es',
    'Spanish (Spain)': 'es',
    'Swedish': 'sv',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Thai': 'th',
    'Tibetan': 'th',
    'Traditional Chinese (Hong Kong, China)': 'zh-TW',
    'Traditional Chinese (Taiwan, China)': 'zh-TW',
    'Turkish': 'tr',
    'Uighur': 'ug',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Vietnamese': 'vi'
}
